version: '3'
services:
  website:
    image: nginx:latest
    container_name: candy
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 80:80
    restart: always

  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "minhasenhasupersecreta"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
